import{a as S,i as f,S as w}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function g(r,o){const i="42276910-5dbc0617c597b0712888fd711",t="https://pixabay.com/api/",a={key:i,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:10};return(await S.get(t,{params:a})).data}function M(r){const{comments:o,downloads:i,views:s,likes:e,webformatURL:t,tags:a,largeImageURL:p}=r;return`<li class="gallery-item">
               <a class="gallery-link" href="${t}">
              <img class="gallery-image" src="${p}" alt="${a}" />
              </a>
              <p><b>Likes: </b>${e}</p>
              <p><b>Views: </b>${s}</p>
              <p><b>Comments: </b>${o}</p>
              <p><b>Downloads: </b>${i}</p>
          </li>`}function E(r){return r.map(M).join("")}const n={formElem:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")};let c,l,u;n.formElem.addEventListener("submit",P);n.loadMoreBtn.addEventListener("click",T);async function P(r){r.preventDefault(),c=r.target.elements.input.value.trim(),u=3,l=1,L();try{const o=await g(c,l);if(o.hits.length===0){f.error({message:"Sorry, there are no images matching your search query. Please try again!2",position:"topRight"}),n.gallery.innerHTML="",u=0,m();return}n.gallery.innerHTML="",y(o.hits)}catch(o){showError(o),n.gallery.innerHTML=""}if(b(),h(),r.target.reset(),!c){f.error({message:"Sorry, there are no images matching your search query. Please try again!1",position:"topRight"}),n.gallery.innerHTML="",m();return}}async function T(){l+=1,L();const r=await g(c,l);y(r.hits),b(),h(),scrollBy({behavior:"smooth",top:"500"})}let d=null;function y(r){const o=E(r);n.gallery.insertAdjacentHTML("beforeend",o),d?d.refresh():d=new w(".gallery a",B)}function v(){n.loadMoreBtn.classList.remove("hidden")}function m(){n.loadMoreBtn.classList.add("hidden")}function h(){l>=u?m():v()}function L(){n.loader.classList.remove("hidden")}function b(){n.loader.classList.add("hidden")}const B={captions:!0,captionType:"attr",captionSelector:"img",captionsData:"alt",captionPosition:"bottom",captionDelay:250};
//# sourceMappingURL=commonHelpers.js.map
